  
version: "3"
services:
  postgres:
    build: postgres/
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=oas
      - POSTGRES_USER=postgres      
      - POSTGRES_PASSWORD=root

    restart: always
    stop_grace_period: 120s
  # APP*****************************************
  springbootapp:
    build: springbootapp/
    expose:
      - 8082
    ports:
      - 8082:8082
    image: springbootapp:2.1.9.RELEASE
    network_mode: bridge
    container_name: springbootapp
    depends_on:
      - postgres
    links:
      - postgres
      
volumes:
  postgres-data: